### ISSUE TITLE
关于启动器自定义分辨率导致无法进入游戏

### ISSUE THREAD

**Issue by BeiziOne** [nekoMC/NekoLauncher#1]
关于启动器第一栏自定义分辨率问题，启动器默认1280*720，但是改成1920*1080就会显示启动器错误。
**界面报错**
![image](https://user-images.githubusercontent.com/71162861/147472648-d70d543b-705c-4c55-b5df-c6125f1d78d3.png)

![image](https://user-images.githubusercontent.com/71162861/147472865-d9299d4e-c535-4851-8992-6fab0f15702d.png)

![image](https://user-images.githubusercontent.com/71162861/147472800-d85e4de0-88be-4450-9d2d-ddbbfa6124d7.png)

**Comment by ChiruMori** [comment]
关联ISSUE：nekoMC/NekoLauncherSrc#14，设置后保存导致主类参数变化进而无法启动。临时解决方案：重装或手动修改 config.json 以下内容：
```
// 错误内容：（调整配置、点保存后发生变化）
"-DFabricMcEmu=",
"net.minecraft.client.main.Main",
""
// 应该修改为：
'-DFabricMcEmu= net.minecraft.client.main.Main ',
```

**Comment by ChiruMori** [comment]
来写代码吧🐛

**Comment by ChiruMori** [comment]
已修复，下次发布会同步修复内容

**Comment by BeiziOne** [comment]
这周工作日把东西先装一下，周末看看怎么写。0.0



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chiru ***@***.***&gt;; 
发送时间: 2021年12月27日(星期一) 晚上11:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [nekoMC/NekoLauncher] 关于启动器自定义分辨率导致无法进入游戏 (Issue #1)





 
来写代码吧🐛
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
